'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
'''

# Generator which yields even fib nums upto 4 million

def evenFibGen():
  a,b = 1,2
  while a <= 4000000:
    if a%2 is 0: yield a
    a,b = b,a+b
    
def main():
  evenfibs = evenFibGen()		#initialize the generator to a variable. 
  fibList = [i for i in evenfibs]
  print "The even fibonacci numbers upto 4 million are {0} and their sum is {1}".format(fibList,sum(fibList))
  
if __name__=='__main__':
  main()